name: vale-linting

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: vale
      uses: errata-ai/vale-action@reviewdog
      with:
        files: docs/
